// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8vrYbAe_Nya2hVQlDdqH3tVzGCFCF4d0',
    appId: '1:138407997184:web:60afdaf3059abced0e0de5',
    messagingSenderId: '138407997184',
    projectId: 'mumbai-hacks-63ecf',
    authDomain: 'mumbai-hacks-63ecf.firebaseapp.com',
    storageBucket: 'mumbai-hacks-63ecf.appspot.com',
    measurementId: 'G-67EVLXKLW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRuHAs6BbsRVpdClkdhzSFTxBbR74y10I',
    appId: '1:138407997184:android:0183cd47fab400c80e0de5',
    messagingSenderId: '138407997184',
    projectId: 'mumbai-hacks-63ecf',
    storageBucket: 'mumbai-hacks-63ecf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVfkaT0sD7QCV1NOzxvHSLxMIvec3iOlA',
    appId: '1:138407997184:ios:3d29b51b06c69ac00e0de5',
    messagingSenderId: '138407997184',
    projectId: 'mumbai-hacks-63ecf',
    storageBucket: 'mumbai-hacks-63ecf.appspot.com',
    iosBundleId: 'com.example.mumbaihacks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVfkaT0sD7QCV1NOzxvHSLxMIvec3iOlA',
    appId: '1:138407997184:ios:3d29b51b06c69ac00e0de5',
    messagingSenderId: '138407997184',
    projectId: 'mumbai-hacks-63ecf',
    storageBucket: 'mumbai-hacks-63ecf.appspot.com',
    iosBundleId: 'com.example.mumbaihacks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8vrYbAe_Nya2hVQlDdqH3tVzGCFCF4d0',
    appId: '1:138407997184:web:1f6728dce438b35a0e0de5',
    messagingSenderId: '138407997184',
    projectId: 'mumbai-hacks-63ecf',
    authDomain: 'mumbai-hacks-63ecf.firebaseapp.com',
    storageBucket: 'mumbai-hacks-63ecf.appspot.com',
    measurementId: 'G-MZNVJVJRWK',
  );
}
